package com.absys.saas.tenant.platform.audit.domain.model;

public enum AuditAction {

    TENANT_CREATED,
    TENANT_UPDATED,

    USER_CREATED,
    USER_UPDATED,
    USER_ACTIVATED,
    USER_DEACTIVATED,

    CUSTOMER_CREATED,
    CUSTOMER_UPDATED,
    CUSTOMER_ACTIVATED,
    CUSTOMER_DEACTIVATED,

    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_ACTIVATED,
    PRODUCT_DEACTIVATED,

    ORDER_CREATED,
    ORDER_CONFIRMED,
    ORDER_CANCELLED,

    SUBSCRIPTION_CREATED,
    SUBSCRIPTION_CANCELLED,

    NOTIFICATION_CREATED
}